name: skore
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.1.3
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter:
    sdk: flutter
  fialogs: ^2.0.4
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  injectable: ^1.5.0
  golden_toolkit: ^0.12.0
  mobx: ^2.0.5

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  mobx_codegen: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf
